import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/*
 * PolygonApplet.java
 *
 * Created on 1. September 2007, 13:31
 */

/**
 *
 * @author  Sunshine
 */
public class PolygonApplet extends javax.swing.JApplet {
    
    public static final int WIDTH = 600;
    public static final int HEIGHT = 500;
   
    private DrawPanel drawPanel;
    
    /** Initializes the applet PolygonApplet */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        setSize(WIDTH, HEIGHT);
        
        drawPanel = new DrawPanel(WIDTH, HEIGHT - 70);
        this.add(drawPanel);
        
        jPanel1.setBounds(0, HEIGHT - 70, WIDTH, 70);
        
        // react on FillPolygon Button
        this.FillPolyBut.addActionListener(new ActionListener()
        {
            public void actionPerformed(ActionEvent evt)
            {
                drawPanel.FillPolygon();
            }
        });
        
        // react on check convexity button
        this.ConvexCheckBut.addActionListener(new ActionListener()
        {
            public void actionPerformed(ActionEvent evt)
            {
                if (!drawPanel.isPolygonClosed())
                {
                    ConvexityLabel.setForeground(Color.BLACK);
                    ConvexityLabel.setText("Polygon not closed!");
                }
                else 
                {
                    if (drawPanel.checkConvexity())
                    {
                        ConvexityLabel.setForeground(Color.GREEN);
                        ConvexityLabel.setText("Polygon is convex!");
                    }
                    else
                    {
                        ConvexityLabel.setForeground(Color.RED);
                        ConvexityLabel.setText("Polygon is NOT convex!");
                    }
                }
            }
        });
        
        this.ClearPolyBut.addActionListener(new ActionListener()
        {
            public void actionPerformed(ActionEvent evt)
            {
                drawPanel.Reset();
            }
        });
        
    }
    
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        FillPolyBut = new javax.swing.JButton();
        ConvexCheckBut = new javax.swing.JButton();
        ClearPolyBut = new javax.swing.JButton();
        ConvexityLabel = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        FillPolyBut.setText("Fill Polygon");
        jPanel1.add(FillPolyBut);
        FillPolyBut.setBounds(10, 40, 130, 23);

        ConvexCheckBut.setText(" Convexity check");
        jPanel1.add(ConvexCheckBut);
        ConvexCheckBut.setBounds(10, 10, 130, 23);

        ClearPolyBut.setText("Clear Polygon");
        jPanel1.add(ClearPolyBut);
        ClearPolyBut.setBounds(200, 40, 130, 23);

        jPanel1.add(ConvexityLabel);
        ConvexityLabel.setBounds(200, 10, 170, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 200, 400, 100);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearPolyBut;
    private javax.swing.JButton ConvexCheckBut;
    private javax.swing.JLabel ConvexityLabel;
    private javax.swing.JButton FillPolyBut;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
